name: testyml
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - requests
      - pyautogui
      - ipython
      - ipywidgets
      - google-api-python-client
      - python-dotenv
      - google-generativeai
      - langchain-core
      - langchain-google-genai
      - openai
      - pywin32
      - pillow

